# Computations for the ISE 201 midterm

In [80]:
import math
import fractions as f
import numpy as np
import pandas as pd
import numpy.linalg as la

## Question 4

One "success" out of the permutations of 3 out of 10  $\ _{10}P_{3}$


In [81]:
f.Fraction(1, (10 * 9 * 8)), '=', 1/ (10 * 9 * 8)

(Fraction(1, 720), '=', 0.001388888888888889)

###  6 successes out of all permutations = combinations of $\binom{10}{3}$

In [82]:
f.Fraction( (3 * 2) , (10 * 9 * 8)), '=', (3 * 2) / (10 * 9 * 8)

(Fraction(1, 120), '=', 0.008333333333333333)

In [83]:
f.Fraction(3*2, 10 * 9* 8)

Fraction(1, 120)

## Question 5



In [84]:
# All subsets of 7 items, if one is required, e.g the null subset is not counted.
pow(2, 7) - 1

127

In [85]:
### All subsets need a bun so its the combinations of the 6 remaining items, but I suppose "just a bun" is allowed
pow(2,6)

64

## Question 7

A vector orthogonal to $(\sqrt 3, \sqrt 3, \sqrt 3)/3 $ is

$(\sqrt 2, - \sqrt 2, 0)/2$  Any rearrangement of elements also works.

With orthonormal vectors, the gram matrix is the identity, so the projection operator reduces to $A A^T$

In [86]:
# Better to make these all unit vectors:
s3 = math.sqrt(3) /3
s2 = math.sqrt(2) /2
x = np.array([1,0,0])

# There are three cases, for the orthogonal vector
A = np.array([[s3,-s2], [s3, 0 ], [s3, s2]])
A

array([[ 0.57735027, -0.70710678],
       [ 0.57735027,  0.        ],
       [ 0.57735027,  0.70710678]])

In [87]:
A.T @ x

array([ 0.57735027, -0.70710678])

In [88]:
# The inverse gram matrix:
la. inv(A.T @ A)

array([[ 1.00000000e+00, -3.39032612e-18],
       [-3.39032612e-18,  1.00000000e+00]])

In [89]:
# One solution
A @ A.T @ x

array([ 0.83333333,  0.33333333, -0.16666667])

In [90]:
# Another solution
A = np.array([[s3,s2], [s3, -s2 ], [s3, 0]])
A @ A.T @ x

array([ 0.83333333, -0.16666667,  0.33333333])

In [91]:
# A third solution
A = np.array([[s3, 0], [s3, -s2 ], [s3, s2]])
A @ A.T @ x

array([0.33333333, 0.33333333, 0.33333333])

In [92]:
# Another orthogonal case
a1 = np.array([1,1,1])/ math.sqrt(3)
a2 = np.array([1,1,-2])/math.sqrt(6)
A = np.vstack([a1,a2]).T
A.T @ A

array([[ 1.00000000e+00, -2.21943272e-17],
       [-2.21943272e-17,  1.00000000e+00]])

In [93]:
A @ A.T @ x

array([5.00000000e-01, 5.00000000e-01, 4.58633852e-19])

## Question 9

Reverse diagonal matrix determinant.

In [94]:
import numpy as np

def rev_diag(n):
  m = np.zeros((n,n))
  m[0,0] = 0.7     # show that adding an off-diagonal element doesn't change anything.
  for k in range(n):
    m[k, n-k-1] = 1
  return m

def odd(n):
  return(n % 2 == 1)

for i in range(1, 10):
  print(i, '\t', np.linalg.det(rev_diag(i)))

1 	 1.0
2 	 -1.0
3 	 -1.0
4 	 1.0
5 	 1.0
6 	 -1.0
7 	 -1.0
8 	 1.0
9 	 1.0


Series of determinant values for reverse diagonals

$(-1)^{1 + (n-1)\ \text{mod}\ 2)}$

In [95]:

pd.DataFrame([pow(-1, 1 + (n -1) // 2) for n in range(10)], index = range(1,11))

0
1   1
2  -1
3  -1
4   1
5   1
6  -1
7  -1
8   1
9   1
10 -1

In [96]:
x = [((n*(n-1))/2) for n in range(1,11)]
[pow((-1),n) for n in x]

[1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0]

runs of 3 items out of 6 identical, sequenced with 4 other identical.